### ISSUE TITLE
Need to add `data_format` to `inputs.exec` section

### ISSUE THREAD

**Issue by CalebFenton** [bertiebaggio/grafana-zfs#1]
This is perhaps only necessary in telegraf 1.19 but I was getting this error:

```
2023-06-09T15:42:09Z E! [inputs.exec] Error in plugin: invalid character 'z' looking for beginning of value
2023-06-09T15:42:09Z E! [telegraf] Error running agent: input plugins recorded 1 errors
```

This is because the output of `zpool_influxdb` was not what telegraf was expecting. According to the docs (https://github.com/influxdata/telegraf/blob/release-1.19/plugins/inputs/exec/README.md) the format looks correct, but they were using the `data_format` directive.

Here's what worked for me (your path may change):

```
[[inputs.exec]]
  commands = ["/usr/bin/zpool_influxdb"]
  timeout = "5s"
  data_format = "influx"
```

**Comment by CalebFenton** [comment]
Also, huge thanks for building this. I'll sleep much better at night knowing my zfs isn't dying. :D

**Comment by bertiebaggio** [comment]
Hi @CalebFenton, thanks for flagging that up. You are absolutely correct:

```cfg
root@artemis:/# grep -A 11 zpool_influxdb /etc/telegraf/telegraf.conf
# # Read metrics from zpool_influxdb
[[inputs.exec]]
#   ## default installation location for zpool_influxdb command
  commands = ["/usr/lib/zfs-linux/zpool_influxdb"]
#   ## Timeout for each command to complete.
  timeout = "5s"
#
#   ## measurement name suffix (for separating different commands)
#   name_suffix = "_mycollector"
#
#   ## Data format to consume.
#   ## Each data format has its own unique set of configuration options, read
#   ## more about them here:
#   ## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md
  data_format = "influx"
```

Good catch.

I'm glad it's useful to you too, I really appreciate you saying so ^_^
